name: Go

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ main ]
jobs:
# Preflight
  preflight-genny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
          
      - name: Install genny
        run: |
          go version
          go get github.com/cheekybits/genny@latest

      - name: generate generics
        run: |
          genny -in ./internal/genny/sarulabsdi/interface-types.go -out ./pkg/interface-types.go -pkg pkg gen "InterfaceType=IHello"

      - name: AutoCommit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply mockgen changes          
          
  build:
    runs-on: ubuntu-latest
    needs: [preflight-genny]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.17'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

